### ISSUE TITLE
Make it easier to test official builds

### ISSUE THREAD

**Issue by arithx** [coreos/fedora-coreos-pipeline#109]
We have a number of things in the pipeline that only run for official builds (such as the `plume` step). When testing changes for these bits we don't have an easy / defined way to perform this, essentially half of the assertions in the `Jenkinsfile` have to be disabled or we have to test the bits individually and merge changes straight through without testing the change in the pipeline.

One simple idea would be something where we have another settable variable hook that we check against as well (e.x.: changing `if (official)` checks to `if (official || official_test)`).

**Comment by jlebon** [comment]
Yeah I feel your pain there. I've definitely butchered the pipeline code in the past just to test my patch.

Before we go any further in this discussion, I think we should put up a "Terminology" section in the README so we don't get confused with the different "types" of pipelines there are. Will draft something up.

**Comment by dustymabe** [comment]
We've re-architected the pipeline quite a bit since this was opened. I think some things are better and some things are probably still the same. Either way this issue is really old and we've found a way to evolve the pipeline over time without this so I'll close it since I don't see anyone working on it anytime soon.
