### ISSUE TITLE
pipeline access

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-pipeline#119]
> If you need access, you can open a bug request at https://bugs.centos.org/ against the Buildsys project and Ci.centos.org Ecosystem Testing category. Do note that the bug-tracker and OpenShift use different authentication backends, so you will have separate credentials for each.

Is...pretty eww.  How hard would it be to make this work like api.ci.openshift.org does, which is Github authentication, and RBAC rules installed for group membership [committed to git](https://github.com/openshift/release/blob/dc7b9ed81a5d7c7ce1551de165eb04cc0150fbba/cluster/ci/config/roles.yaml#L62) or so?

**Comment by jlebon** [comment]
This is more a question for @bstinsonmhk.

**Comment by bstinsonmhk** [comment]
Github auth is not in scope for this infrastructure. But we are working on a self-service portal, tied in with accounts.centos.org. We're also working on Jenkins images that authenticate against ACO and Fedora's FAS, which could help with giving folks access there (if they don't need direct access to the Openshift console)

**Comment by cgwalters** [comment]
I guess nothing stops the FCOS team from configuring the services running inside the cluster (most notably Jenkins) to optionally use Github auth though.

In practice, anyone working on FCOS (and OpenShift upstream, and...a lot of other projects) needs a Github account too.  I [blogged about this before](https://blog.verbum.org/2016/03/23/github-accounts-and-ease-of-contribution/) and not much has changed since then.

**Comment by jlebon** [comment]
> I guess nothing stops the FCOS team from configuring the services running inside the cluster (most notably Jenkins) to optionally use Github auth though.

Oh, I like that idea. I see https://plugins.jenkins.io/github-oauth, and I think we can do this assuming we can still configure it to disallow anonymous view for now (which it looks like we should).

**Comment by jlebon** [comment]
I've been playing with the `github-oauth` plugin (for now in `coreos-ci`, the replacement for `projectatomic-ci`). And while you can tweak authorization knobs per organization & user, surprisingly [*any* GitHub user can authenticate](https://issues.jenkins-ci.org/browse/JENKINS-46962) which is... unsettling. This might fly for our upstream CI projects since they don't have any credentials right now, though I'd be very wary of enabling this on the production pipeline without this fixed.

> We're also working on Jenkins images that authenticate against ACO and Fedora's FAS, which could help with giving folks access there (if they don't need direct access to the Openshift console

This sounds interesting. We don't necessarily need Jenkins images, just some way to hook it up in our Jenkins to use Fedora FAS would be pretty sweet. Does that code already exist?

Annnd yup I see that e.g. https://jenkins-fedora-infra.apps.ci.centos.org/ uses Ipsilon. Nice! Will investigate how that's set up, though I'm guessing it's via the [OpenID plugin](https://wiki.jenkins.io/display/JENKINS/OpenID+plugin).

**Comment by cgwalters** [comment]
OK now that the pipeline/jenkins is in the new OCP 4.4 cluster, I seem to have lost access to both the CoCI jenkins and the fcos pipeline.  I can log into the cluster with `oc` but I don't have any projects either.

**Comment by jlebon** [comment]
The new instructions for this now are:

> If you need access, you can open a pull request to https://pagure.io/fedora-infra/ansible/blob/main/f/playbooks/openshift-apps/fedora-coreos-pipeline.yml with your [Fedora Account System username](https://accounts.fedoraproject.org/) similar to [this one](https://pagure.io/fedora-infra/ansible/pull-request/949).

which I think is OK. So let's close this.
