### ISSUE TITLE
archive stage failing in CCI

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-pipeline#136]
seems like we've started to fail sometimes. I assume it's running out of memory?

```
[fedora-coreos-fedora-coreos-pipeline] Running shell script

+ set -xeuo pipefail

+ coreos-assembler compress --compressor xz

Targeting build: 30.20190916.dev.1

Compressing: builds/30.20190916.dev.1/x86_64

+ xz -c9 -T0 builds/30.20190916.dev.1/x86_64/fedora-coreos-30.20190916.dev.1-qemu.qcow2

+ xz -c9 -T0 builds/30.20190916.dev.1/x86_64/fedora-coreos-30.20190916.dev.1-metal.raw

Error running command xz

script returned exit code 1
```

**Comment by jlebon** [comment]
Hmm, that's likely the case. We should probably add a memory request to our pod spec really.

**Comment by dustymabe** [comment]
from the man page it looks like we can set `XZ_DEFAULTS=--memlimit=150MiB` and change it so that it will use less memory. Ideas for what we should set that value to?

**Comment by jlebon** [comment]
Hmm, I had briefly looked at this, and it seemed like the purpose was so that xz errors out on its own if the limit is reached. But reading more carefully, you're right, it seems like compression at least can respond to it:

> If  the specified memory usage limit is exceeded when decompressing, xz will display an error and
> decompressing the file will fail.  If the limit is exceeded when  compressing,  xz  will  try  to
> scale  the  settings down so that the limit is no longer exceeded (except when using --format=raw
> or --no-adjust).  This way the operation won't fail unless the limit is very small.

So I think if we set a memlimit, as well as request at least that amount in our pod, we should be good to go. We can get a reasonable value to use with e.g. [`time -v`](https://stackoverflow.com/a/774601).
