### ISSUE TITLE
add ostree-container upload support

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-pipeline#359]
Part of https://github.com/coreos/fedora-coreos-tracker/issues/812

Specifically this should build on https://github.com/coreos/fedora-coreos-config/pull/1097

- Detect if `ostree-format: oci`
- Upload the resulting container image to a configurable place (config where?) to e.g. `quay.io/coreos/fedora-coreos:rawhide`

Concerns:

- do we have quay creds set up here?
- How do we handle synchronization?  Do we e.g. upload the container image *after* the s3 sync?

**Comment by jlebon** [comment]
>     * Upload the resulting container image to a configurable place (config where?) to e.g. `quay.io/coreos/fedora-coreos:rawhide`

Meh, we can probably start with hardcoding it in the Groovy for now?

> Concerns:
> 
>     * do we have quay creds set up here?

Yeah, we don't have any yet. We'll have to set it up.

> 
>     * How do we handle synchronization?  Do we e.g. upload the container image _after_ the s3 sync?

I think conceptually this should be part of the release job. I guess right after/in parallel with the [OSTree import request](https://github.com/coreos/fedora-coreos-pipeline/blob/a09346e85f156e663af2232ea96d7ec10ab98bc9/Jenkinsfile.release#L91-L101) (that code only runs for production builds of course, but the image push would just always run since there's no compose/prod distinction there). For mechanical streams like rawhide, the release job is automatically triggered by the build pipeline.

**Comment by cgwalters** [comment]
I don't think I can hack on this due to https://pagure.io/centos-infra/issue/386 - anyone who has access who can take this issue?

**Comment by jlebon** [comment]
I pinged a few folks there. They're pretty responsive usually so let's give it a bit more time?

**Comment by cgwalters** [comment]
OK, I have cluster/jenkins access now.

Does anyone know who owns  https://quay.io/organization/coreos ?  What do we need to create quay.io/coreos/fedora-coreos ?

**Comment by jlebon** [comment]
@bgilbert may have the necessary permissions, or otherwise definitely know who to contact (likely James).

**Comment by cgwalters** [comment]
I've been thinking about this and I think it should go to quay.io/fedora/coreos (i.e. not quay.io/coreos/fcos) - in keeping with [this thread](https://discussion.fedoraproject.org/t/its-more-fedora-than-it-is-fedora-noun/).

**Comment by cgwalters** [comment]
WIP PR in https://github.com/coreos/fedora-coreos-pipeline/pull/383
