### ISSUE TITLE
Cannot push images in OpenShift 4.11

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-pipeline#723]
In a 4.11 cluster, the release job fails with:

```
+ cosa push-container-manifest --auth=**** --repo=quay.io/openshift-release-dev/rhel-coreos-dev --tag=4.12-extensions --tag 412.86.202210272216-0-extensions --artifact=extensions-container --metajsonname=extensions-container --build=412.86.202210272216-0 --arch x86_64
Targeting build: 412.86.202210272216-0
2022-10-28 03:40:14,963 INFO - Running command: ['podman', 'manifest', 'create', 'quay.io/openshift-release-dev/rhel-coreos-dev:4.12-extensions']
...
time="2022-10-28T03:40:15Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
time="2022-10-28T03:40:15Z" level=error msg="cannot find UID/GID for user cosa: no subuid ranges found for user \"cosa\" in /etc/subuid - check rootless mode in man pages."
time="2022-10-28T03:40:15Z" level=warning msg="Using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids if not using a network user"
Error: failed to mount overlay for metacopy check with "" options: permission denied
```

I think this is fallout from [the enablement of the Pod Security Admission in OCP 4.11](https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-auth-pod-security-admission). Part of the change includes defaulting to a tighter `restricted-v2` SCC which by default drops all caps and sets the seccomp profile to `runtime/default` where before the default was `unconfined`. This prevents podman from working. [There is an RFE](https://issues.redhat.com/browse/RFE-2868) for shipping a `nested` SCC for this use case.

Interestingly, the change was ratcheted in such that upgrading clusters still had access to the old `restricted` SCC. But specifically for seccomp, AIUI a pod that doesn't specify a profile will still match `restricted-v2` and not `restricted`. And explicitly setting a seccomp profile is not permitted by the SCC.

**Comment by jlebon** [comment]
Some possible workarounds:
1. Request access to more powerful SCCs. This increases our constraints on the cluster setup. Currently we can work fine with the default restricted SCC and only KVM.
2. Do pushing from supermin. We do this for other privileged operations already. Adds complexity to the cosa code.
3. Do pushing from a worker node, where we have more privs.

We're going to go with the third option for now to get unblocked.

**Comment by dustymabe** [comment]
One workaround I've found is to change my `$HOME` to a different filesystem (`/var/tmp`, which is overlayfs) and it seems to workaround the [offending check](https://github.com/containers/storage/blob/232bf398bd68595d2a6e53ec07d8b3c4424be3c0/drivers/overlay/check.go#L158-L164).

This shouldn't work because there is [another check](https://github.com/containers/storage/blob/232bf398bd68595d2a6e53ec07d8b3c4424be3c0/drivers/overlay/overlay.go#L314-L318) that should fail if we're on an overlay filesystem, but it doesn't in this case (I suspect we're hitting some kind of corner case).

**Comment by dustymabe** [comment]
The better workaround I've found is just using `STORAGE_DRIVER=vfs` for now.

**Comment by cgwalters** [comment]
Yes, we can `STORAGE_DRIVER=vfs` for now; probably the simplest.

Ultimately I think we should work in terms of `oci` directories, and not `containers-storage:`.  We don't need to *unpack* the container images in order to manifest list things.  Unfortunately AFAIK all the podman/buildah family of tools expect to operate on `containers-storage`.  There are other container build tools we can use that can operate on OCI directories.

(The rpm-ostree side writes to an OCI directory directly, it does not use `containers-storage`)

**Comment by dustymabe** [comment]
This should be fixed because https://github.com/coreos/fedora-coreos-pipeline/pull/732 merged.
